### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/dbtools/android/room/sqliteorg/SqliteOrgSQLiteOpenHelper$OpenHelper;

### ISSUE THREAD

**Issue by hansenji** [jeffdcamp/dbtools-room#3]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/dbtools/android/room/sqliteorg/SqliteOrgSQLiteOpenHelper$OpenHelper;
                                                                   at org.dbtools.android.room.sqliteorg.SqliteOrgSQLiteOpenHelper.<init>(SqliteOrgSQLiteOpenHelper.kt:29)
                                                                   at org.dbtools.android.room.sqliteorg.SqliteOrgSQLiteOpenHelperFactory.create(SqliteOrgSQLiteOpenHelperFactory.kt:10)
...
                                                                   at org.dbtools.android.room.sqliteorg.SqliteOrgSQLiteOpenHelper$OpenHelper
                                                                   at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                   at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   	... 59 more
                                                                Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/sqlite/database/sqlite/SQLiteOpenHelper;
                                                                   	... 59 more
                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "org.sqlite.database.sqlite.SQLiteOpenHelper" on path: DexPathList[[zip file "/data/app/org.lds.sni.dev-pUXsEARVN4SN1bYyBNcM0Q==/base.apk"],nativeLibraryDirectories=[/data/app/org.lds.sni.dev-pUXsEARVN4SN1bYyBNcM0Q==/lib/x86, /system/lib, /system/vendor/lib]]
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   	... 59 more

**Comment by hansenji** [comment]
These dependencies are required
```
implementation "org.dbtools:dbtools-room-sqliteorg:$dbtoolsRoomVersion"
implementation 'org.sqlite.sqliteX:sqlite-android:3.15.2'
```
