### ISSUE TITLE
JdbcMemoryCursor doesn't support nullable fields.

### ISSUE THREAD

**Issue by troyhen** [jeffdcamp/dbtools-room#5]
java.lang.IllegalStateException: resultSet.getObject(it) must not be null

	at org.dbtools.android.room.jdbc.JdbcMemoryCursor.readData(JdbcMemoryCursor.kt:59)
	at org.dbtools.android.room.jdbc.JdbcMemoryCursor.<init>(JdbcMemoryCursor.kt:27)
	at org.dbtools.android.room.jdbc.JdbcSQLiteStatement.executeQuery(JdbcSQLiteStatement.kt:36)
	at org.dbtools.android.room.jdbc.JdbcSqliteDatabase.query(JdbcSqliteDatabase.kt:168)
	at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)

**Comment by troyhen** [comment]
I sent the needed changes to Jordan with some other Kotlin optimizations.

**Comment by jeffdcamp** [comment]
Fixed in version 1.3.0
